# Default values for scheduler-plugins-as-a-second-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Note that this is no longer built from the scheduler-plugins repo - it's built
# directly from Kubernetes (in tree)
scheduler:
  name: fluxnetes
  image: ghcr.io/flux-framework/fluxnetes:latest
  replicaCount: 1
  pullPolicy: Always
  leaderElect: false

database:
  image: ghcr.io/flux-framework/fluxnetes-postgres:latest
  pullPolicy: Always

# The sidecar is explicitly the fluxion service. I'd like to
# simplify this to use fluxion as a service
sidecar:
  image: ghcr.io/flux-framework/fluxnetes-sidecar:latest
  policy: lonode
  pullPolicy: Always
  loggingLevel: "9"

  # Port is for GRPC, and enabling the external service will also
  # create the service and ingress to it, along with adding
  # additional API endpoints for our TBA kubectl plugin
  enableExternalService: false
  port: 4242

# NOTE: this can be removed, leaving for now
controller:
  name: scheduler-plugins-controller
  image: registry.k8s.io/scheduler-plugins/controller:v0.28.9
  replicaCount: 1
  nodeSelector: {}
  affinity: {}
  tolerations: []

# LoadVariationRiskBalancing and TargetLoadPacking are not enabled by default
# as they need extra RBAC privileges on metrics.k8s.io.

plugins:
  # We keep this enabled for the custom queue sort
  enabled: ["Fluxnetes"]
  disabled: ["CapacityScheduling","NodeResourceTopologyMatch","NodeResourcesAllocatable","PrioritySort","Coscheduling"] # only in-tree plugins need to be defined here
  # Disable EVERYTHING except for fluxnetes
  # VolumeBinding is required for PreBind, NodeResourcesFit is required or you'll get mismatches
  # Yes - some of these are irrelevant for the use case here, but I'd rather be super
  # conservative and be absolutely sure only fluxnetes is running PreFilter to select nodes
  disabledAll: ["NodePorts", "VolumeRestrictions", "EBSLimits",
                "GCEPDLimits", "NodeVolumeLimits", "AzureDiskLimits", "VolumeZone", 
                "PodTopologySpread", "InterPodAffinity", "NodeAffinity",
                "NodeUnschedulable", "NodeName", "TaintToleration", "DefaultPreemtion",
                "NodeResourcesBalancedAllocation", "ImageLocality"]


enableCertManager: true
kubernetesClusterDomain: cluster.local
webhookService:
  ports:
  - port: 9443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP