kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: scheduler-plugins-controller
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app: scheduler-plugins-controller
  template:
    metadata:
      labels:
        app: scheduler-plugins-controller
    spec:
      serviceAccountName: {{ .Values.controller.name }}
      containers:
      - name: scheduler-plugins-controller
        image: {{ .Values.controller.image }}
        imagePullPolicy: IfNotPresent
      {{- with .Values.controller.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8}}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity: {{- toYaml . | nindent 8}}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations: {{- toYaml . | nindent 8}}
      {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
  name: {{ .Values.scheduler.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: scheduler
  replicas: {{ .Values.scheduler.replicaCount }}
  template:
    metadata:
      labels:
        component: scheduler
        app: fluxnetes-scheduler
    spec:
      serviceAccountName: {{ .Values.scheduler.name }}
      containers:
      - image: {{ .Values.sidecar.image }}
        imagePullPolicy: {{ .Values.sidecar.pullPolicy }}
        command:
        - /go/src/fluxnetes/bin/server
        - --policy={{ .Values.scheduler.policy }}
        - --port={{ .Values.scheduler.port }}
        {{ if .Values.scheduler.enableExternalService }}- --external-service{{ end }}
        name: sidecar
        # These are exposed for the kubectl plugin
        {{ if .Values.scheduler.enableExternalService }}ports:
          - containerPort: {{ .Values.scheduler.port }}
            hostPort: {{ .Values.scheduler.port }}{{ end }}
      - command:
        - /bin/kube-scheduler
        - --config=/etc/kubernetes/scheduler-config.yaml
        image: {{ .Values.scheduler.image }}
        imagePullPolicy: {{ .Values.scheduler.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 15
        name: scheduler-plugins-scheduler
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
        resources:
          requests:
            cpu: '0.1'
        securityContext:
          privileged: false
        volumeMounts:
        - name: scheduler-config
          mountPath: /etc/kubernetes
          readOnly: true
      hostNetwork: false
      hostPID: false
      volumes:
      - name: scheduler-config
        configMap:
          name: scheduler-config
{{ if .Values.scheduler.enableExternalService }}---
apiVersion: v1
kind: Service
metadata:
  name: fluxnetes-service
spec:
  type: NodePort
  selector:
    app: fluxnetes-scheduler
  ports:
  - port: {{ .Values.scheduler.port }}
    targetPort: {{ .Values.scheduler.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fluxnetes-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fluxnetes-service
            port: 
              number: {{ .Values.scheduler.port }}{{ end }}