apiVersion: v1
kind: Pod
metadata:
  name: annotation-second-scheduler
  labels:
    name: multischeduler-example
spec:
  schedulerName: fluence
  containers:
  - name: pod-with-second-annotation-container
    image: registry.k8s.io/pause:2.0