apiVersion: batch/v1
kind: Job
metadata:
  name: job5
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      schedulerName: fluxnetes
      containers:
      - name: job
        image: busybox
        command: [echo, potato]
      restartPolicy: Never
  backoffLimit: 4
