apiVersion: batch/v1
kind: Job
metadata:
  name: job-deadline
spec:
  template:
    spec:
      schedulerName: fluxnetes
      activeDeadlineSeconds: 5
      containers:
      - name: job
        image: busybox
        command: [sleep, "10"]
      restartPolicy: Never
  backoffLimit: 4
