apiVersion: v1
kind: Service
metadata:
  name: {{ include "scheduler-plugins-as-a-second-scheduler.fullname" . }}-webhook-service
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: scheduler-plugins-controller
    app.kubernetes.io/part-of: scheduler-plugins-controller
  {{- include "scheduler-plugins-as-a-second-scheduler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    app: scheduler-plugins-controller
  ports:
    {{- .Values.webhookService.ports | toYaml | nindent 2 -}}
