apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: lammps4-2
spec:
  size: 4
  network: 
    headlessName: l42
  pod:
    schedulerName: fluence
    labels:
      fluence.pod-group: lammps4-2
      fluence.group-size: "4"
  containers:
    - image: ghcr.io/converged-computing/metric-lammps:latest@sha256:e24a1ba8954f5a0a7a0bd854cfc5ca7f82ca12607dc6ace38d838591b8deb8ed
      workingDir: /opt/lammps/examples/reaxff/HNS
      command: lmp -v x 1 -v y 1 -v z 1 -in in.reaxc.hns -nocite
      resources:
        limits:
          cpu: 10
        requests:
          cpu: 10
