apiVersion: v1
kind: Service
metadata:
  name: s0
spec:
  clusterIP: None
  selector:
    job-name: job-0
---
apiVersion: batch/v1
kind: Job
metadata:
  # name will be derived based on iteration
  name: job-0
spec:
  completions: 4
  parallelism: 4
  completionMode: Indexed
  template:
    metadata:
      labels:
        app: job-0        
    spec:
      subdomain: s0
      schedulerName: fluence
      restartPolicy: Never
      containers:
      - name: example-workload
        image: bash:latest
        resources:
          limits:
            cpu: "3"
          requests:
            cpu: "3"
        command:
        - bash
        - -c
        - |
          if [ $JOB_COMPLETION_INDEX -ne "0" ]
            then
              sleep infinity
          fi
          echo "START: $(date +%s)"
          for i in 0 1 2 3
          do
            gotStatus="-1"
            wantStatus="0"             
            while [ $gotStatus -ne $wantStatus ]
            do                      
              ping -c 1 job-0-${i}.s0 > /dev/null 2>&1
              gotStatus=$?                
              if [ $gotStatus -ne $wantStatus ]; then
                echo "Failed to ping pod job-0-${i}.s0, retrying in 1 second..."
                sleep 1
              fi
            done                                                         
            echo "Successfully pinged pod: job-0-${i}.s0"
          done
          echo "DONE: $(date +%s)"